version: '3'

services:
  rstudio:
    image: rocker/verse
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=
    # this option enable access as localhost, inside container
    network_mode: 'host'
